# Generated by Django 4.1.7 on 2023-09-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('dni', models.CharField(default='777777', max_length=8)),
                ('apellidos', models.CharField(default='Apellidos', max_length=100)),
                ('nombres', models.CharField(default='predeterminada', max_length=50)),
                ('telefono', models.CharField(default='77', max_length=10)),
                ('email', models.CharField(default=' predeterminada', max_length=100)),
                ('direccion', models.CharField(default='Dirección predeterminada', max_length=100)),
            ],
        ),
    ]
